In [1]:
import pandas as pd
import numpy as np

In [2]:
books=pd.read_csv('books.csv')

C:\Users\sinek\AppData\Local\Temp\ipykernel_25976\248692396.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books=pd.read_csv('books.csv')

In [3]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [4]:
books.shape

(271360, 8)

In [5]:
books.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [6]:
books=books[['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher', 
      'Image-URL-L']]

In [7]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...

In [8]:
books.rename(columns={
    "Book-Title":"title",
    "Book-Author":'author',
    "Year-Of-Publication":"year",
    "Publisher":"publisher",
    "Image-URL-L":"img_url"},inplace=True)

In [9]:
books.head()

,ISBN,title,author,year,publisher,img_url
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...

In [10]:
users=pd.read_csv('users.csv')

In [11]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [12]:
users.shape

(278858, 3)

In [13]:
ratings=pd.read_csv('ratings.csv')

In [14]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [15]:
ratings.shape

(1149780, 3)

In [16]:
ratings.rename(columns={
    "User-ID":"user_id",
    "Book-Rating":"rating"},inplace=True)

In [17]:
ratings.head()

   user_id        ISBN  rating
0   276725  034545104X       0
1   276726  0155061224       5
2   276727  0446520802       0
3   276729  052165615X       3
4   276729  0521795028       6

In [18]:
 ratings['user_id'].value_counts()

11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...
116180        1
116166        1
116154        1
116137        1
276723        1
Name: user_id, Length: 105283, dtype: int64

In [19]:
ratings['user_id'].unique().shape

(105283,)

In [20]:
x=ratings['user_id'].value_counts()>200

In [21]:
x

11676      True
198711     True
153662     True
98391      True
35859      True
          ...
116180    False
116166    False
116154    False
116137    False
276723    False
Name: user_id, Length: 105283, dtype: bool

In [22]:
x[x].shape

(899,)

In [23]:
y=x[x].index

In [24]:
y

Int64Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352,
            110973, 235105,
            ...
            260183,  73681,  44296, 155916,   9856, 274808,  28634,  59727,
            268622, 188951],
           dtype='int64', length=899)

In [25]:
ratings=ratings[ratings['user_id'].isin(y)]

In [26]:
ratings

         user_id        ISBN  rating
1456      277427  002542730X      10
1457      277427  0026217457       0
1458      277427  003008685X       8
1459      277427  0030615321       0
1460      277427  0060002050       0
...          ...         ...     ...
1147612   275970  3829021860       0
1147613   275970  4770019572       0
1147614   275970   896086097       0
1147615   275970  9626340762       8
1147616   275970  9626344990       0

[526356 rows x 3 columns]

In [27]:
ratings_with_books=ratings.merge(books,on="ISBN")

In [28]:
ratings_with_books.head(2)

,user_id,ISBN,rating,title,author,year,publisher,img_url
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...
1,3363,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...

In [29]:
ratings_with_books.shape

(487671, 8)

In [30]:
num_rating=ratings_with_books.groupby('title')['rating'].count().reset_index()

In [31]:
num_rating.head()

                                               title  rating
0   A Light in the Storm: The Civil War Diary of ...       2
1                              Always Have Popsicles       1
2               Apple Magic (The Collector's series)       1
3   Beyond IBM: Leadership Marketing and Finance ...       1
4   Clifford Visita El Hospital (Clifford El Gran...       1

In [32]:
num_rating.rename(columns={"rating":"num_of_rating"},inplace=True)

In [33]:
num_rating.head()

                                               title  num_of_rating
0   A Light in the Storm: The Civil War Diary of ...              2
1                              Always Have Popsicles              1
2               Apple Magic (The Collector's series)              1
3   Beyond IBM: Leadership Marketing and Finance ...              1
4   Clifford Visita El Hospital (Clifford El Gran...              1

In [34]:
final_rating=ratings_with_books.merge(num_rating,on='title')

In [35]:
final_rating.head(3)

,user_id,ISBN,rating,title,author,year,publisher,img_url,num_of_rating
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82
1,3363,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82
2,11676,002542730X,6,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82

In [36]:
final_rating.shape

(487671, 9)

In [37]:
final_rating=final_rating[final_rating['num_of_rating']>=50]

In [38]:
final_rating.sample(60)

,user_id,ISBN,rating,title,author,year,publisher,img_url,num_of_rating
19997,30972,0446612790,0,2nd Chance,James Patterson,2003,Warner Vision,http://images.amazon.com/images/P/0446612790.0...,124
120607,123981,0425182878,0,Chosen Prey,John Sandford,2004,Berkley Publishing Group,http://images.amazon.com/images/P/0425182878.0...,73
83206,89602,0743431030,5,Mother of Pearl,Melinda Haynes,2001,Pocket,http://images.amazon.com/images/P/0743431030.0...,54
52347,273979,0062502182,0,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,1995,HarperSanFrancisco,http://images.amazon.com/images/P/0062502182.0...,58
1480,163804,0312966091,0,Three To Get Deadly : A Stephanie Plum Novel (...,Janet Evanovich,1998,St. Martin's Paperbacks,http://images.amazon.com/images/P/0312966091.0...,105
108441,36907,0385720106,0,A Map of the World,Jane Hamilton,1999,Anchor Books/Doubleday,http://images.amazon.com/images/P/0385720106.0...,119
192061,145451,0743418131,0,Deck the Halls (Holiday Classics),Mary Higgins Clark,2002,Pocket,http://images.amazon.com/images/P/0743418131.0...,58
75552,159858,0553582143,0,Body of Lies,IRIS JOHANSEN,2003,Bantam,http://images.amazon.com/images/P/0553582143.0...,64
182677,102967,055356160X,0,Cry Wolf,TAMI HOAG,1993,Bantam,http://images.amazon.com/images/P/055356160X.0...,58
96255,258534,0425163407,9,Unnatural Exposure,Patricia Daniels Cornwell,1998,Berkley Publishing Group,http://images.amazon.com/images/P/0425163407.0...,91
92965,7915,0553578308,0,Tough Cookie,Diane Mott Davidson,2001,Bantam Books,http://images.amazon.com/images/P/0553578308.0...,50
75326,11676,0553277472,7,Zen and the Art of Motorcycle Maintenance: An ...,ROBERT PIRSIG,1984,Bantam,http://images.amazon.com/images/P/0553277472.0...,64
109466,208141,0449223612,0,N Is for Noose,Sue Grafton,1999,Fawcett Books,http://images.amazon.com/images/P/0449223612.0...,75
136127,123981,0345369947,0,The Mummy or Ramses the Damned,Anne Rice,1991,Ballantine Books,http://images.amazon.com/images/P/0345369947.0...,83
28581,254465,0373484003,0,Irish Hearts,Nora Roberts,2000,Silhouette,http://images.amazon.com/images/P/0373484003.0...,52
63979,115120,0440219078,0,The Giver (21st Century Reference),LOIS LOWRY,1994,Laure Leaf,http://images.amazon.com/images/P/0440219078.0...,55
129517,50730,0446606324,0,The Winner,David Baldacci,1998,Warner Vision,http://images.amazon.com/images/P/0446606324.0...,80
97783,55492,0671004549,0,You Belong To Me,Mary Higgins Clark,1999,Pocket Books,http://images.amazon.com/images/P/0671004549.0...,56
32684,217375,042513699X,0,Turtle Moon,Alice Hoffman,1993,Berkley Publishing Group,http://images.amazon.com/images/P/042513699X.0...,85
1744,275970,0316096199,0,Lucky : A Memoir,Alice Sebold,2002,Back Bay Books,http://images.amazon.com/images/P/0316096199.0...,115
1714,194600,0316096199,0,Lucky : A Memoir,Alice Sebold,2002,Back Bay Books,http://images.amazon.com/images/P/0316096199.0...,115
95215,70594,1400031362,9,Morality for Beautiful Girls (No.1 Ladies Dete...,Alexander McCall Smith,2002,Anchor,http://images.amazon.com/images/P/1400031362.0...,60
56224,110483,051513287X,0,Face the Fire (Three Sisters Island Trilogy),Nora Roberts,2002,Jove Books,http://images.amazon.com/images/P/051513287X.0...,99
43730,217375,0553580221,0,False Memory,Dean R. Koontz,2000,Bantam Books,http://images.amazon.com/images/P/0553580221.0...,86
144353,30972,044661064X,5,The First Counsel,Brad Meltzer,2001,Warner Vision,http://images.amazon.com/images/P/044661064X.0...,53
73049,28523,0385335881,0,Shopaholic Takes Manhattan (Summer Display Opp...,Sophie Kinsella,2002,Delta,http://images.amazon.com/images/P/0385335881.0...,78
104308,198711,0446360589,0,The Burden of Proof,Scott Turow,1991,Warner Books,http://images.amazon.com/images/P/0446360589.0...,69
165853,114444,0425144429,0,Mr. Murder,Dean R. Koontz,1996,Berkley Publishing Group,http://images.amazon.com/images/P/0425144429.0...,78
140859,234623,0060921145,0,Animal Dreams,Barbara Kingsolver,1991,Perennial,http://images.amazon.com/images/P/0060921145.0...,58
98073,126736,0345386132,5,Eyes of a Child,Richard North Patterson,1996,Ballantine Books,http://images.amazon.com/images/P/0345386132.0...,51
35,130474,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,82
80116,271195,0156027321,0,Life of Pi,Yann Martel,2003,Harvest Books,http://images.amazon.com/images/P/0156027321.0...,185
101962,113519,0688177751,0,Miss Julia Speaks Her Mind : A Novel,Ann B. Ross,2000,Perennial,http://images.amazon.com/images/P/0688177751.0...,61
89920,95903,0767914767,10,The Devil Wears Prada : A Novel,LAUREN WEISBERGER,2004,Broadway Books,http://images.amazon.com/images/P/0767914767.0...,75
65897,108005,1573225789,0,The Color of Water: A Black Man's Tribute to H...,James McBride,1997,Riverhead Books,http://images.amazon.com/images/P/1573225789.0...,84
8340,235842,0446603716,0,Hide &amp; Seek,James Patterson,1996,Warner Books,http://images.amazon.com/images/P/0446603716.0...,64
57424,133689,0151001006,0,Snow Falling on Cedars,David Guterson,1994,Harcourt,http://images.amazon.com/images/P/0151001006.0...,206
38292,174304,0446608955,0,A Walk to Remember,Nicholas Sparks,2000,Warner Books,http://images.amazon.com/images/P/0446608955.0...,137
54308,69971,038542017X,7,Like Water for Chocolate : A Novel in Monthly ...,LAURA ESQUIVEL,1995,Anchor,http://images.amazon.com/images/P/038542017X.0...,55
80542,238120,0345424719,0,A Widow for One Year,JOHN IRVING,1999,Ballantine Books,http://images.amazon.com/images/P/0345424719.0...,97
118548,266226,0312924585,8,Silence of the Lambs,Thomas Harris,1991,St. Martin's Press,http://images.amazon.com/images/P/0312924585.0...,113
35724,115003,0440236673,0,The Brethren,John Grisham,2000,Island,http://images.amazon.com/images/P/0440236673.0...,169
1862,153662,0316284955,9,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,2000,Back Bay Books,http://images.amazon.com/images/P/0316284955.0...,114
31567,274808,0385722206,0,Balzac and the Little Chinese Seamstress : A N...,DAI SIJIE,2002,Anchor,http://images.amazon.com/images/P/0385722206.0...,111
121901,7346,0449219364,8,G Is for Gumshoe (Kinsey Millhone Mysteries (P...,Sue Grafton,1991,Fawcett Books,http://images.amazon.com/images/P/0449219364.0...,82
54711,254,043935806X,0,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,2003,Scholastic,http://images.amazon.com/images/P/043935806X.0...,105
2116,22625,0316666343,10,The Lovely Bones: A Novel,Alice Sebold,2002,"Little, Brown",http://images.amazon.com/images/P/0316666343.0...,270
29564,260897,0375725784,10,A Heartbreaking Work of Staggering Genius,Dave Eggers,2001,Vintage Books USA,http://images.amazon.com/images/P/0375725784.0...,67
47018,2766,0671617028,0,The Color Purple,Alice Walker,1985,Pocket Books,http://images.amazon.com/images/P/0671617028.0...,118
80094,229011,0156027321,0,Life of Pi,Yann Martel,2003,Harvest Books,http://images.amazon.com/images/P/0156027321.0...,185
5844,175003,0425158616,0,Cause of Death,Patricia Daniels Cornwell,1997,Berkley Publishing Group,http://images.amazon.com/images/P/0425158616.0...,121
12836,265115,0804108749,0,Saint Maybe,ANNE TYLER,1992,Ivy Books,http://images.amazon.com/images/P/0804108749.0...,73
129903,230522,067102423X,0,Bag of Bones,Stephen King,1999,Pocket,http://images.amazon.com/images/P/067102423X.0...,54
166568,48494,0515135062,0,Three Fates,Nora Roberts,2004,Jove Books,http://images.amazon.com/images/P/0515135062.0...,81
1826,85656,0316284955,0,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,2000,Back Bay Books,http://images.amazon.com/images/P/0316284955.0...,114
34564,170518,044021145X,0,The Firm,John Grisham,1992,Bantam Dell Publishing Group,http://images.amazon.com/images/P/044021145X.0...,227
86716,102967,006101351X,0,The Perfect Storm : A True Story of Men Agains...,Sebastian Junger,1998,HarperTorch,http://images.amazon.com/images/P/006101351X.0...,163
91581,145165,0449221490,0,L Is for Lawless,Sue Grafton,1996,Fawcett Books,http://images.amazon.com/images/P/0449221490.0...,70
52462,207782,014028009X,8,Bridget Jones's Diary,Helen Fielding,1999,Penguin Books,http://images.amazon.com/images/P/014028009X.0...,277
59780,178667,0440241537,0,The King of Torts,JOHN GRISHAM,2003,Dell,http://images.amazon.com/images/P/0440241537.0...,117

In [39]:
final_rating['img_url'][6558]

'http://images.amazon.com/images/P/043936213X.01.LZZZZZZZ.jpg'

In [40]:
final_rating.shape

(61853, 9)

In [41]:
final_rating.drop_duplicates(['user_id','title'],inplace=True)

In [42]:
final_rating.shape

(59850, 9)

In [43]:

book_pivot=final_rating.pivot_table(columns='user_id',index='title',values='rating')

In [44]:
book_pivot

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84 Charing Cross Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,7.0,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
book_pivot.fillna(0,inplace=True)

In [46]:
book_pivot

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [47]:
from scipy.sparse import csr_matrix

In [48]:
book_sparse=csr_matrix(book_pivot)

In [49]:
book_sparse

<742x888 sparse matrix of type '<class 'numpy.float64'>'
	with 14942 stored elements in Compressed Sparse Row format>

In [50]:
from sklearn.neighbors import NearestNeighbors
model=NearestNeighbors(algorithm='brute')

In [51]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [52]:
distance,suggestion=model.kneighbors(book_pivot.iloc[237,:].values.reshape(1,-1),n_neighbors=6)

In [53]:
distance

array([[ 0.        , 68.78953409, 69.5413546 , 72.64296249, 76.83098333,
        77.28518616]])

In [54]:
suggestion

array([[237, 240, 238, 241, 184, 536]], dtype=int64)

In [55]:
for i in range(len(suggestion)):
    print(book_pivot.index[suggestion[i]])

Index(['Harry Potter and the Chamber of Secrets (Book 2)',
       'Harry Potter and the Prisoner of Azkaban (Book 3)',
       'Harry Potter and the Goblet of Fire (Book 4)',
       'Harry Potter and the Sorcerer's Stone (Book 1)', 'Exclusive',
       'The Cradle Will Fall'],
      dtype='object', name='title')

In [56]:
book_pivot.index

Index(['1984', '1st to Die: A Novel', '2nd Chance', '4 Blondes',
       '84 Charing Cross Road', 'A Bend in the Road', 'A Case of Need',
       'A Child Called \It\": One Child's Courage to Survive"',
       'A Civil Action', 'A Cry In The Night',
       ...
       'Winter Solstice', 'Wish You Well', 'Without Remorse',
       'Wizard and Glass (The Dark Tower, Book 4)', 'Wuthering Heights',
       'Year of Wonders', 'You Belong To Me',
       'Zen and the Art of Motorcycle Maintenance: An Inquiry into Values',
       'Zoya', '\O\" Is for Outlaw"'],
      dtype='object', name='title', length=742)

In [57]:
# Export the index to a list and print it
book_titles = book_pivot.index.tolist()
for title in book_titles:
    print(title)

1984
1st to Die: A Novel
2nd Chance
4 Blondes
84 Charing Cross Road
A Bend in the Road
A Case of Need
A Child Called \It\": One Child's Courage to Survive"
A Civil Action
A Cry In The Night
A Darkness More Than Night
A Day Late and a Dollar Short
A Fine Balance
A Great Deliverance
A Heartbreaking Work of Staggering Genius
A Is for Alibi (Kinsey Millhone Mysteries (Paperback))
A Lesson Before Dying (Vintage Contemporaries (Paperback))
A Man Named Dave: A Story of Triumph and Forgiveness
A Man in Full
A Map of the World
A Painted House
A Patchwork Planet
A Prayer for Owen Meany
A Thin Dark Line (Mysteries &amp; Horror)
A Thousand Acres (Ballantine Reader's Circle)
A Time to Kill
A Virtuous Woman (Oprah's Book Club (Paperback))
A Walk to Remember
A Widow for One Year
A Wrinkle In Time
A Wrinkle in Time
A Year in Provence
ANGELA'S ASHES
Abduction
About a Boy
Absolute Power
Acceptable Risk
Accident
Airframe
Alaska
All Around the Town
All Creatures Great and Small
All I Really Need to Know
All That Remains (Kay Scarpetta Mysteries (Paperback))
All the Pretty Horses (The Border Trilogy, Vol 1)
Along Came a Spider (Alex Cross Novels)
American Gods
And Then You Die
Angela's Ashes (MMP) : A Memoir
Angela's Ashes: A Memoir
Angels
Angels &amp; Demons
Angus, Thongs and Full-Frontal Snogging: Confessions of Georgia Nicolson
Animal Dreams
Animal Farm
Anne Frank: The Diary of a Young Girl
Anne of Avonlea (Anne of Green Gables Novels (Paperback))
Anne of Green Gables (Anne of Green Gables Novels (Paperback))
Anne of the Island
Artemis Fowl (Artemis Fowl, Book 1)
Ashes to Ashes
At Home in Mitford (The Mitford Years)
Atonement : A Novel
B Is for Burglar (Kinsey Millhone Mysteries (Paperback))
Back Roads
Bag of Bones
Balzac and the Little Chinese Seamstress : A Novel
Bastard Out of Carolina
Beach House
Beach Music
Before I Say Good-Bye
Bel Canto: A Novel
Beloved
Beloved (Plume Contemporary Fiction)
Betrayal in Death
Big Cherry Holler: A Big Stone Gap Novel (Ballantine Reader's Circle)
Big Stone Gap: A Novel (Ballantine Reader's Circle)
Big Trouble
Billy Straight : A Novel
Birthright
Bittersweet
Black House
Black Notice
Black and Blue
Bleachers
Blessings
Blood Work
Blue Diary
Body of Evidence (Kay Scarpetta Mysteries (Paperback))
Body of Lies
Brave New World
Breath, Eyes, Memory
Breathing Lessons
Bridge to Terabithia
Bridget Jones : The Edge of Reason
Bridget Jones's Diary
Bridget Jones: The Edge of Reason
By the Light of the Moon
C Is for Corpse (Kinsey Millhone Mysteries (Paperback))
CAT'S EYE
Call of the Wild
Carnal Innocence
Carolina Moon
Carrie
Cat &amp; Mouse (Alex Cross Novels)
Catering to Nobody
Cause of Death
Certain Prey
Charlotte's Web (Trophy Newbery)
Charming Billy
Chicken Soup for the Soul (Chicken Soup for the Soul)
Chicken Soup for the Woman's Soul (Chicken Soup for the Soul Series (Paper))
Chocolat
Choke
Chosen Prey
Christine
Chromosome 6
Circle of Friends
Clear and Present Danger (Jack Ryan Novels)
Cold Mountain
Cold Mountain : A Novel
Cold Sassy Tree
Colony
Coming Home
Confessions of a Shopaholic (Summer Display Opportunity)
Confessions of an Ugly Stepsister : A Novel
Congo
Contact
Contagion
Coraline
Couplehood
Cradle and All
Crazy for You
Cruel &amp; Unusual (Kay Scarpetta Mysteries (Paperback))
Cry Wolf
Cujo
D Is for Deadbeat (Kinsey Millhone Mysteries (Paperback))
Daddy
Daddy's Little Girl
Daisy Fay and the Miracle Man
Dance upon the Air (Three Sisters Island Trilogy)
Dances With Wolves
Dangerous
Dark Angel
Dark Paradise
Dark Rivers of the Heart
Dawn (Cutler)
Dead Run
Death du Jour
Debt of Honor (Jack Ryan Novels)
Deception Point
Deck the Halls (Holiday Classics)
Degree of Guilt
Deja Dead
Desperation
Devices and Desires
Different Seasons
Digital Fortress : A Thriller
Disclosure
Divine Secrets of the Ya-Ya Sisterhood: A Novel
Dolores Claiborne
Don't Stand Too Close to a Naked Man
Don't Sweat the Small Stuff and It's All Small Stuff : Simple Ways to Keep the Little Things from Taking Over Your Life (Don't Sweat the Small Stuff Series)
Dr. Atkins' New Diet Revolution
Dragon Tears
Dragonfly in Amber
Dream Country
Dreamcatcher
Drowning Ruth
Drowning Ruth (Oprah's Book Club)
Drums of Autumn
Dude, Where's My Country?
Dust to Dust
Dying for Chocolate (Culinary Mysteries (Paperback))
E Is for Evidence: A Kinsey Millhone Mystery (Kinsey Millhone Mysteries (Paperback))
Easy Prey
Echoes
Ellen Foster
Empire Falls
Ender's Game (Ender Wiggins Saga (Paperback))
Engaging The Enemy
Envy
Evening Class
Everything's Eventual : 14 Dark Tales
Exclusive
Executive Orders (Jack Ryan Novels)
Eyes of Prey
Eyes of a Child
F Is for Fugitive (Kinsey Millhone Mysteries (Paperback))
FORREST GUMP (Movie Tie in)
Face the Fire (Three Sisters Island Trilogy)
Fahrenheit 451
Faking It
Fall On Your Knees (Oprah #45)
Falling Angels
False Memory
Family Album
Fast Food Nation: The Dark Side of the All-American Meal
Fast Women
Fat Tuesday
Fatal Cure
Fatherhood
Fear Nothing
Final Target
Fine Things
Fingersmith
Five Days in Paris
Five Quarters of the Orange
Flesh and Blood
Forever... : A Novel of Good and Evil, Love and Hope
Fortune's Rocks : A Novel
Fortune's Rocks: A Novel
Foucault's Pendulum
Four Blind Mice
Four Past Midnight
Four To Score (A Stephanie Plum Novel)
Fried Green Tomatoes at the Whistle Stop Cafe
From Potter's Field
From the Corner of His Eye
Full House (Janet Evanovich's Full Series)
Full Tilt (Janet Evanovich's Full Series)
G Is for Gumshoe (Kinsey Millhone Mysteries (Paperback))
GARDEN OF SHADOWS (Dollanger Saga (Paperback))
Gerald's Game
Girl in Hyacinth Blue
Girl with a Pearl Earring
Girl, Interrupted
Good Omens
Good in Bed
Gorky Park
Granny Dan
Guardian Angel
Guilty Pleasures (Anita Blake Vampire Hunter (Paperback))
Guilty as Sin
H Is for Homicide (Kinsey Millhone Mysteries (Paperback))
Hannibal
Hard Eight : A Stephanie Plum Novel (A Stephanie Plum Novel)
Harry Potter and the Chamber of Secrets (Book 2)
Harry Potter and the Goblet of Fire (Book 4)
Harry Potter and the Order of the Phoenix (Book 5)
Harry Potter and the Prisoner of Azkaban (Book 3)
Harry Potter and the Sorcerer's Stone (Book 1)
Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))
Harvest
Heart of the Sea (Irish Trilogy)
Heartbeat
Heartbreaker
Hearts In Atlantis
Hearts in Atlantis
Heaven and Earth (Three Sisters Island Trilogy)
Hemlock Bay
Here on Earth
Hide &amp; Seek
Hideaway
High Fidelity
High Five (A Stephanie Plum Novel)
Holes (Yearling Newbery)
Homecoming
Homeport
Hornet's Nest
Hot Six : A Stephanie Plum Novel (A Stephanie Plum Novel)
House of Sand and Fog
How Stella Got Her Groove Back
How to Be Good
How to Make an American Quilt
I Capture the Castle
I Is for Innocent
I Know This Much Is True
I Know This Much Is True (Oprah's Book Club)
I Know Why the Caged Bird Sings
I'll Be Seeing You
Icebound
Icy Sparks
If Only It Were True
If Tomorrow Comes
Impulse
In Her Shoes : A Novel
Inner Harbor (Quinn Brothers (Paperback))
Insomnia
Intensity
Interview with the Vampire
Into Thin Air : A Personal Account of the Mt. Everest Disaster
Into the Wild
Invasion
Irish Hearts
Isle of Dogs
It
It Was on Fire When I Lay Down on It
It's Always Something
J Is for Judgment
Jack &amp; Jill (Alex Cross Novels)
Jacob Have I Loved
Jemima J: A Novel About Ugly Ducklings and Swans
Jewel
Jewel (Oprah's Book Club)
Jewels of the Sun (Irish Trilogy)
Journey
Jurassic Park
K Is for Killer (Kinsey Millhone Mysteries (Paperback))
Kaleidoscope
Key of Knowledge (Key Trilogy (Paperback))
Key of Light (Key Trilogy (Paperback))
Key of Valor (Roberts, Nora. Key Trilogy, 3.)
Killjoy
Kiss the Girls
L Is for Lawless
Ladder of Years
Lake Wobegon Days
Lake Wobegon days
Lamb : The Gospel According to Biff, Christ's Childhood Pal
Last Chance Saloon
Last Man Standing
Left Behind: A Novel of the Earth's Last Days (Left Behind No. 1)
Let Me Call You Sweetheart
Life of Pi
Lightning
Like Water for Chocolate : A Novel in Monthly Installments with Recipes, Romances, and Home Remedies
Like Water for Chocolate: A Novel in Monthly Installments With Recipes, Romances and Home Remedies
Like Water for Chocolate: A Novel in Monthly Installments, With Recipes, Romances, and Home Remedies
Little Altars Everywhere: A Novel
Long After Midnight
Lord of the Flies
Love in the Time of Cholera (Penguin Great Books of the 20th Century)
Loves Music, Loves to Dance
Lucky : A Memoir
Lucky Man: A Memoir
M Is for Malice
Macgregor Brides (Macgregors)
Macgregor Grooms (Macgregors)
Master of the Game
Matilda
Me Talk Pretty One Day
Men Are from Mars, Women Are from Venus: A Practical Guide for Improving Communication and Getting What You Want in Your Relationships
Mercy
Message from Nam
Message in a Bottle
Middlesex: A Novel
Midnight
Midnight Bayou
Midnight in the Garden of Good and Evil
Midnight in the Garden of Good and Evil: A Savannah Story
Midwives: A Novel
Mind Prey
Mirror Image
Misery
Miss Julia Speaks Her Mind : A Novel
Monster : A Novel (Alex Delaware Novels (Paperback))
Montana Sky
Moo
Moonlight Becomes You
Morality for Beautiful Girls (No.1 Ladies Detective Agency)
Mortal Fear
Mortal Prey
Mother of Pearl
Mr. Murder
My Gal Sunday
Mystic River
N Is for Noose
Naked
Needful Things
Nerd in Shining Armor
Neuromancer (Remembering Tomorrow)
Neverwhere
Nickel and Dimed: On (Not) Getting By in America
Nicolae: The Rise of Antichrist (Left Behind No. 3)
Night
Night Prey
Night Sins
Night Whispers
Nightmares &amp; Dreamscapes
Nights in Rodanthe
No Greater Love
No Safe Place
Notes from a Small Island
Nothing Lasts Forever
Now You See Her
On the Street Where You Live
One Door Away from Heaven
One True Thing
One for the Money (A Stephanie Plum Novel)
One for the Money (Stephanie Plum Novels (Paperback))
Oryx and Crake
Outlander
Over the Edge
P Is for Peril
Paradise
Patriot Games (Jack Ryan Novels)
Pay It Forward
Peace Like a River
Pet Sematary
Phantoms
Pigs in Heaven
Plainsong (Vintage Contemporaries)
Pleading Guilty
Plum Island
Point of Origin
Politically Correct Bedtime Stories: Modern Tales for Our Life and Times
Pop Goes the Weasel
Portrait in Death
Possession : A Romance
Postmortem
Practical Magic
Presumed Innocent
Pretend You Don't See Her
Pride and Prejudice
Primary Colors: A Novel of Politics
Prime Cut
Prodigal Summer
Prodigal Summer: A Novel
Purity in Death
Q Is for Quarry
Quentins
Rainbow Six
Range of Motion
Reap the Wind
Rebecca
Red Dragon
Red Storm Rising
Remember Me
Riptide
Rising Sun
Rising Tides
River's End
River, Cross My Heart
Rose Madder
Roses Are Red (Alex Cross Novels)
Rules of Prey
SHIPPING NEWS
STONES FROM THE RIVER
Sacred Sins
Saint Maybe
Sanctuary
Saving Faith
Scarlet Feather
Scarlett : The Sequel to Margaret Mitchell's \Gone With the Wind\""
Schindler's List
Sea Glass: A Novel
Sea Swept (Quinn Brothers (Paperback))
Seabiscuit
Seabiscuit: An American Legend
Second Nature
Secret History
Secrets
Seize the Night
September
Seven Habits Of Highly Effective People
Seven Up (A Stephanie Plum Novel)
Shadow Prey
Shadowfires
Shattered
She's Come Undone (Oprah's Book Club (Paperback))
She's Come Undone (Oprah's Book Club)
Shell Seekers
Shopaholic Takes Manhattan (Summer Display Opportunity)
Shopaholic Ties the Knot
Sick Puppy
Silence of the Lambs
Silent Witness
Sisterhood of the Traveling Pants
Skeleton Crew
Skipping Christmas
Slammerkin
Slaughterhouse Five or the Children's Crusade: A Duty Dance With Death
Sleepers
Slow Waltz in Cedar Bend
Small Town Girl
Smart Women
Smilla's Sense of Snow
Snow Falling on Cedars
Sole Survivor
Song of Solomon (Oprah's Book Club (Paperback))
Songs in Ordinary Time (Oprah's Book Club (Paperback))
Sophie's World: A Novel About the History of Philosophy
Southern Cross
Sphere
Standoff
Stanislaski Brothers (Silhouette Promo)
Still Waters
Stillwatch
Strangers
Stupid White Men ...and Other Sorry Excuses for the State of the Nation!
Sudden Prey
Summer Pleasures
Summer Sisters
Suzanne's Diary for Nicholas
Table For Two
Tales of a Fourth Grade Nothing
Taltos: Lives of the Mayfair Witches
Tara Road
Tears of the Giraffe (No.1 Ladies Detective Agency)
Tears of the Moon (Irish Trilogy)
Tell Me Lies (Tell Me Lies)
Tell Me Your Dreams
Tell No One
Temptation
That Camden Summer
The Accidental Tourist
The Alchemist: A Fable About Following Your Dream
The Alibi
The Alienist
The Amazing Adventures of Kavalier &amp; Clay
The Amber Spyglass (His Dark Materials, Book 3)
The Andromeda Strain
The Angel of Darkness
The Apprentice
The Bachelor (Warner Books Contemporary Romance)
The Bad Beginning (A Series of Unfortunate Events, Book 1)
The Bad Place
The Beach House
The Bean Trees
The Blind Assassin
The Blue Nowhere : A Novel
The Bluest Eye
The Body Farm
The Bonesetter's Daughter
The Bonfire of the Vanities
The Book of Ruth (Oprah's Book Club (Paperback))
The Bourne Identity
The Bourne Supremacy
The Bourne Ultimatum
The Boy Next Door
The Brethren
The Bridges of Madison County
The Burden of Proof
The Cardinal of the Kremlin (Jack Ryan Novels)
The Carousel
The Catcher in the Rye
The Celestine Prophecy (Celestine Prophecy)
The Chamber
The Cider House Rules
The Clan of the Cave Bear (Earth's Children (Paperback))
The Client
The Clinic (Alex Delaware Novels (Paperback))
The Color Purple
The Color of Water: A Black Man's Tribute to His White Mother
The Copper Beech
The Cradle Will Fall
The Crimson Petal and the White
The Da Vinci Code
The Dark Half
The Dead Zone
The Deep End of the Ocean
The Devil Wears Prada : A Novel
The Diary of Ellen Rimbauer: My Life at Rose Red
The Divine Secrets of the Ya-Ya Sisterhood: A Novel
The Dogs of Babel (Today Show Book Club #12)
The Door to December
The Drawing of the Three (The Dark Tower, Book 2)
The Edge
The Eight
The Empty Chair
The English Patient
The Eyre Affair: A Novel
The Face of Deception
The Fellowship of the Ring (The Lord of the Rings, Part 1)
The Firm
The First Counsel
The First Wives Club Movie Tie In
The Five People You Meet in Heaven
The Fourth Hand
The General's Daughter
The Genesis Code
The Ghost
The Gift
The Girl Who Loved Tom Gordon
The Girls' Guide to Hunting and Fishing
The Giver (21st Century Reference)
The Glass Lake
The God of Small Things
The Golden Compass (His Dark Materials, Book 1)
The Great Gatsby
The Green Mile
The Grilling Season
The Guardian
The Gunslinger (The Dark Tower, Book 1)
The Handmaid's Tale
The Hitchhiker's Guide to the Galaxy
The Hobbit : The Enchanting Prelude to The Lord of the Rings
The Honk and Holler Opening Soon
The Horse Whisperer
The Hot Zone
The Hours : A Novel
The Hours: A Novel
The House of the Spirits
The Hundred Secret Senses
The Hunt for Red October
The Idiot Girls' Action Adventure Club
The Jester
The Joy Luck Club
The Killing Game: Only One Can Win...and the Loser Dies
The King of Torts
The Kiss
The Kitchen God's Wife
The Last Precinct
The Last Time They Met : A Novel
The Little Friend
The Little Prince
The Long Road Home
The Loop
The Lost Boy: A Foster Child's Search for the Love of a Family
The Lost World

The Lottery Winner : Alvirah And Willy Stories
The Lovely Bones: A Novel
The Mists of Avalon
The Most Wanted
The Mulberry Tree
The Mummy or Ramses the Damned
The Murder Book
The Nanny Diaries: A Novel
The Next Accident
The No. 1 Ladies' Detective Agency (Today Show Book Club #8)
The Notebook
The Other Boleyn Girl
The Partner
The Pelican Brief
The Perfect Storm : A True Story of Men Against the Sea
The Phantom Tollbooth
The Pillars of the Earth
The Pilot's Wife : A Novel
The Plains of Passage (Earth's Children (Paperback))
The Poisonwood Bible
The Poisonwood Bible: A Novel
The Prince of Tides
The Princess Bride: S Morgenstern's Classic Tale of True Love and High Adventure
The Promise
The Pull of the Moon
The Queen of the Damned (Vampire Chronicles (Paperback))
The Rainmaker
The Rapture of Canaan
The Reader
The Red Tent (Bestselling Backlist)
The Reef
The Regulators
The Reptile Room (A Series of Unfortunate Events, Book 2)
The Rescue
The Return Journey
The Return of the King (The Lord of the Rings, Part 3)
The Robber Bride
The Runaway Jury
The Sands of Time
The Saving Graces: A Novel
The Search
The Secret Garden
The Secret Life of Bees
The Shining
The Shipping News : A Novel
The Simple Truth
The Smoke Jumper
The Stone Diaries
The Street Lawyer
The Subtle Knife (His Dark Materials, Book 2)
The Sum of All Fears (Jack Ryan Novels)
The Summerhouse
The Summons
The Surgeon
The Sweet Potato Queens' Book of Love
The Switch
The Tale of the Body Thief (Vampire Chronicles (Paperback))
The Talisman
The Tao of Pooh
The Temple of My Familiar
The Terminal Man
The Testament
The Thorn Birds
The Tommyknockers
The Two Towers (The Lord of the Rings, Part 2)
The Ugly Duckling
The Valley of Horses
The Vampire Lestat (Vampire Chronicles, Book II)
The Villa
The Virgin Suicides
The Wedding
The Weight of Water : A Novel Tag: Author of Resistance and Strange Fits of Passion
The Winner
The Witching Hour (Lives of the Mayfair Witches)
The Witness
The Woman Next Door
Thinner
Three Fates
Three Junes
Three To Get Deadly : A Stephanie Plum Novel (A Stephanie Plum Novel)
Timeline
Tis : A Memoir
Tis: A Memoir
To Kill a Mockingbird
To the Nines: A Stephanie Plum Novel
Tom Clancy's Op-Center (Tom Clancy's Op Center (Paperback))
Touching Evil
Tough Cookie
Toxin
Tribulation Force: The Continuing Drama of Those Left Behind (Left Behind No. 2)
Truly, Madly Manhattan
Tuesdays with Morrie: An Old Man, a Young Man, and Life's Greatest Lesson
Turtle Moon
Two for the Dough
Under the Tuscan Sun
Unnatural Exposure
Unspeakable
Vanished
Vector
Vinegar Hill (Oprah's Book Club (Paperback))
Violets Are Blue
Violin
Vittorio the Vampire: New Tales of the Vampires
Voyager
WLD ACCORDNG GARP
Waiting to Exhale
Wanderlust
Watchers
Watermelon
Watership Down
We Were the Mulvaneys
We'll Meet Again
Weep No More My Lady
Welcome to Temptation
Welcome to the World, Baby Girl!
What Looks Like Crazy On An Ordinary Day
What to Expect When You're Expecting (Revised Edition)
When the Wind Blows
Where the Heart Is (Oprah's Book Club (Paperback))
Where the Red Fern Grows
While I Was Gone
While My Pretty One Sleeps
Whirlwind (Tyler, Book 1)
Whispers
White Oleander : A Novel
White Oleander : A Novel (Oprah's Book Club)
White Teeth: A Novel
Wicked: The Life and Times of the Wicked Witch of the West
Wifey
Wild Animus
Winter Moon
Winter Solstice
Wish You Well
Without Remorse
Wizard and Glass (The Dark Tower, Book 4)
Wuthering Heights
Year of Wonders
You Belong To Me
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values
Zoya
\O\" Is for Outlaw"

In [58]:
books_name=book_pivot.index

In [59]:
def recommend_book(book_name):
    # Check if the provided book title is in the dataset
    if book_name not in book_pivot.index:
        print(f"Book '{book_name}' not found in the dataset.")
        return
    
    # Continue with the recommendation process for valid books
    book_id = np.where(book_pivot.index == book_name)[0][0]
    distance, suggestion = model.kneighbors(book_pivot.iloc[book_id, :].values.reshape(1, -1), n_neighbors=6)
    
    print(f"Recommendations for '{book_name}':")
    for i in range(len(suggestion)):
        books = book_pivot.index[suggestion[i]]
        for j in books:
            print(j)

In [60]:
book_name='Harry Potter and the Goblet of Fire (Book 4)'
recommend_book(book_name)

Recommendations for 'Harry Potter and the Goblet of Fire (Book 4)':
Harry Potter and the Goblet of Fire (Book 4)
Harry Potter and the Prisoner of Azkaban (Book 3)
Harry Potter and the Order of the Phoenix (Book 5)
The Cradle Will Fall
Exclusive
Tough Cookie